/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package br.com.gbf.Gl3DViewerForAndroid;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int font=0x7f020000;
        public static final int font2=0x7f020001;
        public static final int font2_sem_alpha=0x7f020002;
        public static final int font2_sem_alpha2=0x7f020003;
        public static final int icon=0x7f020004;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int bridge=0x7f040000;
        public static final int cube=0x7f040001;
        public static final int cube_test=0x7f040002;
        public static final int diamond=0x7f040003;
        public static final int penguin=0x7f040004;
        public static final int triangles=0x7f040005;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
}
